// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `tokio_runtime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// POC: моковые новости для проверки FFI.
List<StoringNews> mockNewsList() =>
    RustLib.instance.api.crateApiSimpleMockNewsList();

/// Инициализация ядра с SQLite.
Future<void> initCore({required String dbPath}) =>
    RustLib.instance.api.crateApiSimpleInitCore(dbPath: dbPath);

Future<void> setToken({required String token}) =>
    RustLib.instance.api.crateApiSimpleSetToken(token: token);

Future<String?> getToken() => RustLib.instance.api.crateApiSimpleGetToken();

/// Валидация формата токена (UUID v4). Возвращает текст ошибки или null если ОК.
String? checkTokenFormat({required String token}) =>
    RustLib.instance.api.crateApiSimpleCheckTokenFormat(token: token);

/// Получить URL логотипа компании по тикеру. Null если тикер неизвестен.
String? tickerIconUrl({required String ticker}) =>
    RustLib.instance.api.crateApiSimpleTickerIconUrl(ticker: ticker);

/// Реальная проверка токена через сервер WebSocket (TokenResultOk / TokenResultInvalid).
/// Возвращает null если токен принят, либо текст ошибки.
Future<String?> validateToken({required String token}) =>
    RustLib.instance.api.crateApiSimpleValidateToken(token: token);

/// Открывает WS-соединение и шлёт события через sink. Flutter получает это
/// как Stream<NewsStreamEvent>. Sink закрывается при отписке в Dart.
Stream<NewsStreamEvent> startNewsStream({required String token}) =>
    RustLib.instance.api.crateApiSimpleStartNewsStream(token: token);

Future<List<StoringNews>> readAllNews() =>
    RustLib.instance.api.crateApiSimpleReadAllNews();

/// Вкл/выкл источник по имени. Сохраняется в SQLite.
Future<void> setSourceEnabled(
        {required String sourceName, required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetSourceEnabled(
        sourceName: sourceName, enabled: enabled);

/// Возвращает user-overrides: список (source_name, enabled).
/// Источник считается "по умолчанию" если его нет в этом списке.
Future<List<(String, bool)>> getSourceSettings() =>
    RustLib.instance.api.crateApiSimpleGetSourceSettings();

/// Фильтр черный/белый по тикерам/хэштегам/фразам.
/// filter_type ∈ { tickers_black, tickers_white, hashtags_black, hashtags_white,
///                  phrases_black, phrases_white }
Future<void> setFilter(
        {required String filterType,
        required bool enabled,
        required List<String> values}) =>
    RustLib.instance.api.crateApiSimpleSetFilter(
        filterType: filterType, enabled: enabled, values: values);

/// Возвращает фильтр: (enabled, values).
Future<(bool, List<String>)> getFilter({required String filterType}) =>
    RustLib.instance.api.crateApiSimpleGetFilter(filterType: filterType);

/// Применить текущие фильтры: true если новость отфильтрована.
Future<bool> newsIsFiltered({required StoringNews news}) =>
    RustLib.instance.api.crateApiSimpleNewsIsFiltered(news: news);

/// Сохранить DSL подсветки.
Future<void> setTextHighlightDsl({required String dsl}) =>
    RustLib.instance.api.crateApiSimpleSetTextHighlightDsl(dsl: dsl);

/// Загрузить DSL подсветки.
Future<String> getTextHighlightDsl() =>
    RustLib.instance.api.crateApiSimpleGetTextHighlightDsl();

/// Включена ли подсветка слов и фраз.
Future<bool> getTextHighlightEnabled() =>
    RustLib.instance.api.crateApiSimpleGetTextHighlightEnabled();

/// Переключатель подсветки слов и фраз.
Future<void> setTextHighlightEnabled({required bool enabled}) =>
    RustLib.instance.api
        .crateApiSimpleSetTextHighlightEnabled(enabled: enabled);

/// Выбранная тема: "dark" / "light" / "system".
Future<String> getThemeMode() =>
    RustLib.instance.api.crateApiSimpleGetThemeMode();

/// Сохранить выбор темы.
Future<void> setThemeMode({required String mode}) =>
    RustLib.instance.api.crateApiSimpleSetThemeMode(mode: mode);

/// Включены ли системные push-уведомления о новостях.
Future<bool> getPushEnabled() =>
    RustLib.instance.api.crateApiSimpleGetPushEnabled();

/// Переключатель push-уведомлений.
Future<void> setPushEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleSetPushEnabled(enabled: enabled);

/// Сохранить список алертов: пары (хэштеги, имя звука).
Future<void> setHashtagAlerts({required List<(List<String>, String)> alerts}) =>
    RustLib.instance.api.crateApiSimpleSetHashtagAlerts(alerts: alerts);

/// Загрузить список алертов.
Future<List<(List<String>, String)>> getHashtagAlerts() =>
    RustLib.instance.api.crateApiSimpleGetHashtagAlerts();

/// Вернуть имя звука для алерта, соответствующего хэштегам новости,
/// либо None если ни один алерт не подходит.
Future<String?> matchingAlertSound({required List<String> newsTags}) =>
    RustLib.instance.api.crateApiSimpleMatchingAlertSound(newsTags: newsTags);

@freezed
sealed class NewsStreamEvent with _$NewsStreamEvent {
  const NewsStreamEvent._();

  const factory NewsStreamEvent.connecting() = NewsStreamEvent_Connecting;
  const factory NewsStreamEvent.connected() = NewsStreamEvent_Connected;
  const factory NewsStreamEvent.disconnected() = NewsStreamEvent_Disconnected;
  const factory NewsStreamEvent.error(
    String field0,
  ) = NewsStreamEvent_Error;

  /// Полный reload списка (NewsHistory от сервера).
  const factory NewsStreamEvent.newsReset(
    List<StoringNews> field0,
  ) = NewsStreamEvent_NewsReset;

  /// Одна новая новость.
  const factory NewsStreamEvent.newsAdded(
    StoringNews field0,
  ) = NewsStreamEvent_NewsAdded;

  /// Обновление существующей новости (сервер прислал NewsChange).
  const factory NewsStreamEvent.newsUpdated(
    StoringNews field0,
  ) = NewsStreamEvent_NewsUpdated;

  /// Удаление по id.
  const factory NewsStreamEvent.newsDeleted(
    Uint32List field0,
  ) = NewsStreamEvent_NewsDeleted;

  /// Пришёл обновлённый каталог источников (TokenResultOk).
  const factory NewsStreamEvent.sourceListUpdated(
    List<SourceGroup> field0,
  ) = NewsStreamEvent_SourceListUpdated;

  /// Токен используется другим клиентом — UI показывает баннер.
  const factory NewsStreamEvent.sessionTakenOver(
    String field0,
  ) = NewsStreamEvent_SessionTakenOver;
}

/// Группа источников (None = «Базовые»).
class SourceGroup {
  final String? groupName;
  final List<SourceItem> sources;

  const SourceGroup({
    this.groupName,
    required this.sources,
  });

  @override
  int get hashCode => groupName.hashCode ^ sources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceGroup &&
          runtimeType == other.runtimeType &&
          groupName == other.groupName &&
          sources == other.sources;
}

/// Один источник новостей для UI.
class SourceItem {
  final String sourceName;
  final bool defaultEnabled;

  const SourceItem({
    required this.sourceName,
    required this.defaultEnabled,
  });

  @override
  int get hashCode => sourceName.hashCode ^ defaultEnabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceItem &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          defaultEnabled == other.defaultEnabled;
}

/// Новость — mirror of stocksi_core::types::news::StoringNews для Dart.
class StoringNews {
  final int id;
  final PlatformInt64? timestamp;
  final String title;
  final String? short;
  final String? source;
  final List<String> tickers;
  final List<String> tags;
  final List<String> files;
  final String? fullTextLink;

  const StoringNews({
    required this.id,
    this.timestamp,
    required this.title,
    this.short,
    this.source,
    required this.tickers,
    required this.tags,
    required this.files,
    this.fullTextLink,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      timestamp.hashCode ^
      title.hashCode ^
      short.hashCode ^
      source.hashCode ^
      tickers.hashCode ^
      tags.hashCode ^
      files.hashCode ^
      fullTextLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoringNews &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          timestamp == other.timestamp &&
          title == other.title &&
          short == other.short &&
          source == other.source &&
          tickers == other.tickers &&
          tags == other.tags &&
          files == other.files &&
          fullTextLink == other.fullTextLink;
}
