// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1220866399;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_stocksi_mobile',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  String? crateApiSimpleCheckTokenFormat({required String token});

  Future<(bool, List<String>)> crateApiSimpleGetFilter(
      {required String filterType});

  Future<List<(List<String>, String)>> crateApiSimpleGetHashtagAlerts();

  Future<bool> crateApiSimpleGetPushEnabled();

  Future<List<(String, bool)>> crateApiSimpleGetSourceSettings();

  Future<String> crateApiSimpleGetTextHighlightDsl();

  Future<bool> crateApiSimpleGetTextHighlightEnabled();

  Future<String> crateApiSimpleGetThemeMode();

  Future<String?> crateApiSimpleGetToken();

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiSimpleInitCore({required String dbPath});

  Future<String?> crateApiSimpleMatchingAlertSound(
      {required List<String> newsTags});

  List<StoringNews> crateApiSimpleMockNewsList();

  Future<bool> crateApiSimpleNewsIsFiltered({required StoringNews news});

  Future<List<StoringNews>> crateApiSimpleReadAllNews();

  Future<void> crateApiSimpleSetFilter(
      {required String filterType,
      required bool enabled,
      required List<String> values});

  Future<void> crateApiSimpleSetHashtagAlerts(
      {required List<(List<String>, String)> alerts});

  Future<void> crateApiSimpleSetPushEnabled({required bool enabled});

  Future<void> crateApiSimpleSetSourceEnabled(
      {required String sourceName, required bool enabled});

  Future<void> crateApiSimpleSetTextHighlightDsl({required String dsl});

  Future<void> crateApiSimpleSetTextHighlightEnabled({required bool enabled});

  Future<void> crateApiSimpleSetThemeMode({required String mode});

  Future<void> crateApiSimpleSetToken({required String token});

  Stream<NewsStreamEvent> crateApiSimpleStartNewsStream(
      {required String token});

  String? crateApiSimpleTickerIconUrl({required String ticker});

  Future<String?> crateApiSimpleValidateToken({required String token});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String? crateApiSimpleCheckTokenFormat({required String token}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(token, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleCheckTokenFormatConstMeta,
      argValues: [token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleCheckTokenFormatConstMeta =>
      const TaskConstMeta(
        debugName: "check_token_format",
        argNames: ["token"],
      );

  @override
  Future<(bool, List<String>)> crateApiSimpleGetFilter(
      {required String filterType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filterType, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_bool_list_string,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetFilterConstMeta,
      argValues: [filterType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetFilterConstMeta => const TaskConstMeta(
        debugName: "get_filter",
        argNames: ["filterType"],
      );

  @override
  Future<List<(List<String>, String)>> crateApiSimpleGetHashtagAlerts() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_record_list_string_string,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetHashtagAlertsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetHashtagAlertsConstMeta =>
      const TaskConstMeta(
        debugName: "get_hashtag_alerts",
        argNames: [],
      );

  @override
  Future<bool> crateApiSimpleGetPushEnabled() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetPushEnabledConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetPushEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "get_push_enabled",
        argNames: [],
      );

  @override
  Future<List<(String, bool)>> crateApiSimpleGetSourceSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_record_string_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetSourceSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetSourceSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "get_source_settings",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleGetTextHighlightDsl() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetTextHighlightDslConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetTextHighlightDslConstMeta =>
      const TaskConstMeta(
        debugName: "get_text_highlight_dsl",
        argNames: [],
      );

  @override
  Future<bool> crateApiSimpleGetTextHighlightEnabled() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetTextHighlightEnabledConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetTextHighlightEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "get_text_highlight_enabled",
        argNames: [],
      );

  @override
  Future<String> crateApiSimpleGetThemeMode() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetThemeModeConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetThemeModeConstMeta => const TaskConstMeta(
        debugName: "get_theme_mode",
        argNames: [],
      );

  @override
  Future<String?> crateApiSimpleGetToken() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleGetTokenConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGetTokenConstMeta => const TaskConstMeta(
        debugName: "get_token",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitCore({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleInitCoreConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitCoreConstMeta => const TaskConstMeta(
        debugName: "init_core",
        argNames: ["dbPath"],
      );

  @override
  Future<String?> crateApiSimpleMatchingAlertSound(
      {required List<String> newsTags}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(newsTags, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleMatchingAlertSoundConstMeta,
      argValues: [newsTags],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleMatchingAlertSoundConstMeta =>
      const TaskConstMeta(
        debugName: "matching_alert_sound",
        argNames: ["newsTags"],
      );

  @override
  List<StoringNews> crateApiSimpleMockNewsList() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_storing_news,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleMockNewsListConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleMockNewsListConstMeta => const TaskConstMeta(
        debugName: "mock_news_list",
        argNames: [],
      );

  @override
  Future<bool> crateApiSimpleNewsIsFiltered({required StoringNews news}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_storing_news(news, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleNewsIsFilteredConstMeta,
      argValues: [news],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleNewsIsFilteredConstMeta =>
      const TaskConstMeta(
        debugName: "news_is_filtered",
        argNames: ["news"],
      );

  @override
  Future<List<StoringNews>> crateApiSimpleReadAllNews() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_storing_news,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleReadAllNewsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleReadAllNewsConstMeta => const TaskConstMeta(
        debugName: "read_all_news",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleSetFilter(
      {required String filterType,
      required bool enabled,
      required List<String> values}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filterType, serializer);
        sse_encode_bool(enabled, serializer);
        sse_encode_list_String(values, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetFilterConstMeta,
      argValues: [filterType, enabled, values],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetFilterConstMeta => const TaskConstMeta(
        debugName: "set_filter",
        argNames: ["filterType", "enabled", "values"],
      );

  @override
  Future<void> crateApiSimpleSetHashtagAlerts(
      {required List<(List<String>, String)> alerts}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_record_list_string_string(alerts, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetHashtagAlertsConstMeta,
      argValues: [alerts],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetHashtagAlertsConstMeta =>
      const TaskConstMeta(
        debugName: "set_hashtag_alerts",
        argNames: ["alerts"],
      );

  @override
  Future<void> crateApiSimpleSetPushEnabled({required bool enabled}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(enabled, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetPushEnabledConstMeta,
      argValues: [enabled],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetPushEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_push_enabled",
        argNames: ["enabled"],
      );

  @override
  Future<void> crateApiSimpleSetSourceEnabled(
      {required String sourceName, required bool enabled}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sourceName, serializer);
        sse_encode_bool(enabled, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetSourceEnabledConstMeta,
      argValues: [sourceName, enabled],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetSourceEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_source_enabled",
        argNames: ["sourceName", "enabled"],
      );

  @override
  Future<void> crateApiSimpleSetTextHighlightDsl({required String dsl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dsl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetTextHighlightDslConstMeta,
      argValues: [dsl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetTextHighlightDslConstMeta =>
      const TaskConstMeta(
        debugName: "set_text_highlight_dsl",
        argNames: ["dsl"],
      );

  @override
  Future<void> crateApiSimpleSetTextHighlightEnabled({required bool enabled}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(enabled, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetTextHighlightEnabledConstMeta,
      argValues: [enabled],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetTextHighlightEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_text_highlight_enabled",
        argNames: ["enabled"],
      );

  @override
  Future<void> crateApiSimpleSetThemeMode({required String mode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetThemeModeConstMeta,
      argValues: [mode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetThemeModeConstMeta => const TaskConstMeta(
        debugName: "set_theme_mode",
        argNames: ["mode"],
      );

  @override
  Future<void> crateApiSimpleSetToken({required String token}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(token, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiSimpleSetTokenConstMeta,
      argValues: [token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleSetTokenConstMeta => const TaskConstMeta(
        debugName: "set_token",
        argNames: ["token"],
      );

  @override
  Stream<NewsStreamEvent> crateApiSimpleStartNewsStream(
      {required String token}) {
    final sink = RustStreamSink<NewsStreamEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(token, serializer);
        sse_encode_StreamSink_news_stream_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleStartNewsStreamConstMeta,
      argValues: [token, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleStartNewsStreamConstMeta =>
      const TaskConstMeta(
        debugName: "start_news_stream",
        argNames: ["token", "sink"],
      );

  @override
  String? crateApiSimpleTickerIconUrl({required String ticker}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(ticker, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleTickerIconUrlConstMeta,
      argValues: [ticker],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleTickerIconUrlConstMeta =>
      const TaskConstMeta(
        debugName: "ticker_icon_url",
        argNames: ["ticker"],
      );

  @override
  Future<String?> crateApiSimpleValidateToken({required String token}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(token, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleValidateTokenConstMeta,
      argValues: [token],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleValidateTokenConstMeta =>
      const TaskConstMeta(
        debugName: "validate_token",
        argNames: ["token"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<NewsStreamEvent> dco_decode_StreamSink_news_stream_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  StoringNews dco_decode_box_autoadd_storing_news(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_storing_news(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(List<String>, String)> dco_decode_list_record_list_string_string(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_list_string_string)
        .toList();
  }

  @protected
  List<(String, bool)> dco_decode_list_record_string_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_bool).toList();
  }

  @protected
  List<SourceGroup> dco_decode_list_source_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_source_group).toList();
  }

  @protected
  List<SourceItem> dco_decode_list_source_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_source_item).toList();
  }

  @protected
  List<StoringNews> dco_decode_list_storing_news(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_storing_news).toList();
  }

  @protected
  NewsStreamEvent dco_decode_news_stream_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return const NewsStreamEvent_Connecting();
      case 1:
        return const NewsStreamEvent_Connected();
      case 2:
        return const NewsStreamEvent_Disconnected();
      case 3:
        return NewsStreamEvent_Error(
          dco_decode_String(raw[1]),
        );
      case 4:
        return NewsStreamEvent_NewsReset(
          dco_decode_list_storing_news(raw[1]),
        );
      case 5:
        return NewsStreamEvent_NewsAdded(
          dco_decode_box_autoadd_storing_news(raw[1]),
        );
      case 6:
        return NewsStreamEvent_NewsUpdated(
          dco_decode_box_autoadd_storing_news(raw[1]),
        );
      case 7:
        return NewsStreamEvent_NewsDeleted(
          dco_decode_list_prim_u_32_strict(raw[1]),
        );
      case 8:
        return NewsStreamEvent_SourceListUpdated(
          dco_decode_list_source_group(raw[1]),
        );
      case 9:
        return NewsStreamEvent_SessionTakenOver(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  (bool, List<String>) dco_decode_record_bool_list_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_bool(arr[0]),
      dco_decode_list_String(arr[1]),
    );
  }

  @protected
  (List<String>, String) dco_decode_record_list_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_list_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  (String, bool) dco_decode_record_string_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_bool(arr[1]),
    );
  }

  @protected
  SourceGroup dco_decode_source_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SourceGroup(
      groupName: dco_decode_opt_String(arr[0]),
      sources: dco_decode_list_source_item(arr[1]),
    );
  }

  @protected
  SourceItem dco_decode_source_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SourceItem(
      sourceName: dco_decode_String(arr[0]),
      defaultEnabled: dco_decode_bool(arr[1]),
    );
  }

  @protected
  StoringNews dco_decode_storing_news(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return StoringNews(
      id: dco_decode_u_32(arr[0]),
      timestamp: dco_decode_opt_box_autoadd_i_64(arr[1]),
      title: dco_decode_String(arr[2]),
      short: dco_decode_opt_String(arr[3]),
      source: dco_decode_opt_String(arr[4]),
      tickers: dco_decode_list_String(arr[5]),
      tags: dco_decode_list_String(arr[6]),
      files: dco_decode_list_String(arr[7]),
      fullTextLink: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<NewsStreamEvent> sse_decode_StreamSink_news_stream_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  StoringNews sse_decode_box_autoadd_storing_news(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_storing_news(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(List<String>, String)> sse_decode_list_record_list_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(List<String>, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_list_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, bool)> sse_decode_list_record_string_bool(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, bool)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_bool(deserializer));
    }
    return ans_;
  }

  @protected
  List<SourceGroup> sse_decode_list_source_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SourceGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_source_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<SourceItem> sse_decode_list_source_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SourceItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_source_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<StoringNews> sse_decode_list_storing_news(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoringNews>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_storing_news(deserializer));
    }
    return ans_;
  }

  @protected
  NewsStreamEvent sse_decode_news_stream_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return const NewsStreamEvent_Connecting();
      case 1:
        return const NewsStreamEvent_Connected();
      case 2:
        return const NewsStreamEvent_Disconnected();
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return NewsStreamEvent_Error(var_field0);
      case 4:
        var var_field0 = sse_decode_list_storing_news(deserializer);
        return NewsStreamEvent_NewsReset(var_field0);
      case 5:
        var var_field0 = sse_decode_box_autoadd_storing_news(deserializer);
        return NewsStreamEvent_NewsAdded(var_field0);
      case 6:
        var var_field0 = sse_decode_box_autoadd_storing_news(deserializer);
        return NewsStreamEvent_NewsUpdated(var_field0);
      case 7:
        var var_field0 = sse_decode_list_prim_u_32_strict(deserializer);
        return NewsStreamEvent_NewsDeleted(var_field0);
      case 8:
        var var_field0 = sse_decode_list_source_group(deserializer);
        return NewsStreamEvent_SourceListUpdated(var_field0);
      case 9:
        var var_field0 = sse_decode_String(deserializer);
        return NewsStreamEvent_SessionTakenOver(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (bool, List<String>) sse_decode_record_bool_list_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_bool(deserializer);
    var var_field1 = sse_decode_list_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (List<String>, String) sse_decode_record_list_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_list_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, bool) sse_decode_record_string_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_bool(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SourceGroup sse_decode_source_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_groupName = sse_decode_opt_String(deserializer);
    var var_sources = sse_decode_list_source_item(deserializer);
    return SourceGroup(groupName: var_groupName, sources: var_sources);
  }

  @protected
  SourceItem sse_decode_source_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceName = sse_decode_String(deserializer);
    var var_defaultEnabled = sse_decode_bool(deserializer);
    return SourceItem(
        sourceName: var_sourceName, defaultEnabled: var_defaultEnabled);
  }

  @protected
  StoringNews sse_decode_storing_news(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_timestamp = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_short = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_opt_String(deserializer);
    var var_tickers = sse_decode_list_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_files = sse_decode_list_String(deserializer);
    var var_fullTextLink = sse_decode_opt_String(deserializer);
    return StoringNews(
        id: var_id,
        timestamp: var_timestamp,
        title: var_title,
        short: var_short,
        source: var_source,
        tickers: var_tickers,
        tags: var_tags,
        files: var_files,
        fullTextLink: var_fullTextLink);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_news_stream_event_Sse(
      RustStreamSink<NewsStreamEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_news_stream_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_storing_news(
      StoringNews self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_storing_news(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_list_string_string(
      List<(List<String>, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_list_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_bool(
      List<(String, bool)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_bool(item, serializer);
    }
  }

  @protected
  void sse_encode_list_source_group(
      List<SourceGroup> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_source_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_source_item(
      List<SourceItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_source_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_storing_news(
      List<StoringNews> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_storing_news(item, serializer);
    }
  }

  @protected
  void sse_encode_news_stream_event(
      NewsStreamEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NewsStreamEvent_Connecting():
        sse_encode_i_32(0, serializer);
      case NewsStreamEvent_Connected():
        sse_encode_i_32(1, serializer);
      case NewsStreamEvent_Disconnected():
        sse_encode_i_32(2, serializer);
      case NewsStreamEvent_Error(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case NewsStreamEvent_NewsReset(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_list_storing_news(field0, serializer);
      case NewsStreamEvent_NewsAdded(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_box_autoadd_storing_news(field0, serializer);
      case NewsStreamEvent_NewsUpdated(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_box_autoadd_storing_news(field0, serializer);
      case NewsStreamEvent_NewsDeleted(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_list_prim_u_32_strict(field0, serializer);
      case NewsStreamEvent_SourceListUpdated(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_list_source_group(field0, serializer);
      case NewsStreamEvent_SessionTakenOver(field0: final field0):
        sse_encode_i_32(9, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_record_bool_list_string(
      (bool, List<String>) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.$1, serializer);
    sse_encode_list_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_list_string_string(
      (List<String>, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_bool(
      (String, bool) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_bool(self.$2, serializer);
  }

  @protected
  void sse_encode_source_group(SourceGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.groupName, serializer);
    sse_encode_list_source_item(self.sources, serializer);
  }

  @protected
  void sse_encode_source_item(SourceItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceName, serializer);
    sse_encode_bool(self.defaultEnabled, serializer);
  }

  @protected
  void sse_encode_storing_news(StoringNews self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_opt_box_autoadd_i_64(self.timestamp, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.short, serializer);
    sse_encode_opt_String(self.source, serializer);
    sse_encode_list_String(self.tickers, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_list_String(self.files, serializer);
    sse_encode_opt_String(self.fullTextLink, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
